### ISSUE TITLE
GitHub

### ISSUE THREAD

**Issue by ItzSomebody** [ItzSomebody/DirectLeaks-AntiReleak-Remover#1]
Wow, GitHub, stop ruining my tabbing

**Comment by OpticFusion1** [comment]
*updates this for spigot, directleaks and blackspigot* they all use the same anti-piracy measures last time i checked, obviously it won't be public, though i think there are already software that does remove the more recent anti-piracy measures for DL and BS, don't really plan on leaking anything, although it allows me to make a good base for when someone decides to bring up an anti-piracy idea *shrug*
